### ISSUE TITLE
[BUG] Launching the utility without firefox installed before on the host

### ISSUE THREAD

**Issue by bojeanson** [octo-technology/awscli-saml-sso#2]
**Describe the bug**
The utility crashes when launching it in a brand-new python venv. (No Firefox installed on the host)

**To Reproduce**
1. Create a venv on the host : `python3.8 -m venv my-venv`
2. Activate it : `source my-venv/bin/activate`
3. Install the module : `pip install awscli-saml-sso`
4. Launch the utility : `awscli_saml_sso`

**Expected behavior**
To get to the webpage on which to set our accenture credentials.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Python 3.8.1

**Additional context**
```
awscli_saml_sso
Please configure your identity provider url [https://<fqdn>:<port>/adfs/ls/IdpInitiatedSignOn.aspx?loginToRp=urn:amazon:webservices]:
https://federation-sts.accenture.com/adfs/ls/idpinitiatedsignon.aspx?loginToRp=urn:amazon:webservices
[WDM] - There is no [macos] geckodriver for browser  in cache
INFO:WDM:There is no [macos] geckodriver for browser  in cache
[WDM] - Getting latest mozilla release info for v0.28.0
INFO:WDM:Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-macos.tar.gz
INFO:WDM:Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-macos.tar.gz
[WDM] - Driver has been saved in cache [/Users/baptiste.ojeanson/.wdm/drivers/geckodriver/macos/v0.28.0]
INFO:WDM:Driver has been saved in cache [/Users/baptiste.ojeanson/.wdm/drivers/geckodriver/macos/v0.28.0]
Waiting for AWS SAML homepage...Traceback (most recent call last):
  File "/Users/baptiste.ojeanson/Desktop/benjam-outils/bin/awscli_saml_sso", line 10, in <module>
    sys.exit(main())
  File "/Users/baptiste.ojeanson/Desktop/benjam-outils/lib/python3.8/site-packages/awscli_saml_sso/__main__.py", line 30, in main
    browser = webdriver.Firefox(executable_path=GeckoDriverManager().install(), service_log_path=devnull)
  File "/Users/baptiste.ojeanson/Desktop/benjam-outils/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/Users/baptiste.ojeanson/Desktop/benjam-outils/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/baptiste.ojeanson/Desktop/benjam-outils/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/baptiste.ojeanson/Desktop/benjam-outils/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/baptiste.ojeanson/Desktop/benjam-outils/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
```

**Comment by bojeanson** [comment]
<img width="1680" alt="Capture d’écran 2020-12-02 à 11 37 45" src="https://user-images.githubusercontent.com/10031569/100861982-dba7aa00-3492-11eb-83b6-cef0e60ee930.png">
